version: '3'
services:
  app:
    image: openjdk:latest
    ports:
      - 80:8080
    environment:
      - FFMPEG_PATH=/usr/local/bin/ffmpeg
    volumes:
      - ./build/libs:/app
    command: java -jar /app/your-application.jar